// Copies the built-in icon set and bundled fonts out of node_modules into src/.
// Run with `npm run vendor` after changing the lists below; the output is committed
// so the app never needs node_modules or a network connection at runtime.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const nm = path.join(root, 'node_modules');

// room.json icon name -> Tabler outline icon file (MIT licensed)
const ICONS = {
  golf: 'golf', flag: 'flag-2', target: 'target', trophy: 'trophy', crown: 'crown',
  theater: 'movie', tv: 'device-tv', 'tv-old': 'device-tv-old', ticket: 'ticket', play: 'player-play',
  video: 'video', camera: 'camera', photo: 'photo',
  games: 'device-gamepad', gamepad: 'device-gamepad-2', xbox: 'brand-xbox', steam: 'brand-steam', twitch: 'brand-twitch',
  music: 'music', radio: 'radio', headphones: 'headphones', mic: 'microphone-2', speaker: 'device-speaker',
  web: 'world', www: 'world-www', news: 'news', leaderboard: 'list-numbers', chart: 'chart-bar',
  netflix: 'brand-netflix', youtube: 'brand-youtube', spotify: 'brand-spotify', amazon: 'brand-amazon',
  disney: 'brand-disney', apple: 'brand-apple',
  plane: 'plane', flight: 'plane-departure', wind: 'wind', satellite: 'satellite', antenna: 'antenna', wifi: 'wifi',
  weather: 'cloud-rain', cloud: 'cloud', sun: 'sun', moon: 'moon', temperature: 'temperature',
  settings: 'settings', adjustments: 'adjustments', tools: 'tools', power: 'power', sleep: 'zzz',
  restart: 'refresh', exit: 'logout', door: 'door-exit', lock: 'lock', home: 'home', back: 'arrow-left',
  desktop: 'device-desktop', laptop: 'device-laptop', volume: 'volume', 'volume-low': 'volume-2', mute: 'volume-3',
  apps: 'apps', grid: 'layout-grid', folder: 'folder', sparkles: 'sparkles', star: 'star', heart: 'heart',
  bulb: 'bulb', bolt: 'bolt', clock: 'clock', stopwatch: 'stopwatch', calendar: 'calendar',
  user: 'user', users: 'users', 'map-pin': 'map-pin', car: 'car', bike: 'bike', run: 'run', swim: 'swimming',
  football: 'ball-football', basketball: 'ball-basketball', tennis: 'ball-tennis', baseball: 'ball-baseball',
  'american-football': 'ball-american-football',
  beer: 'beer', drink: 'glass-full', coffee: 'coffee', pizza: 'pizza',
};

const iconDir = path.join(nm, '@tabler/icons/icons/outline');
const icons = {};
for (const [name, file] of Object.entries(ICONS)) {
  const svg = fs.readFileSync(path.join(iconDir, file + '.svg'), 'utf8');
  // keep only the drawable children; the renderer supplies the <svg> wrapper
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '')
    .replace(/\s*\n\s*/g, '').trim();
  icons[name] = inner;
}
const iconOut = path.join(root, 'src/renderer/vendor/icons.js');
fs.mkdirSync(path.dirname(iconOut), { recursive: true });
fs.writeFileSync(iconOut,
  '// Generated by scripts/vendor-assets.mjs from Tabler Icons (MIT, https://tabler.io/icons). Do not edit.\n' +
  'export const ICONS = ' + JSON.stringify(icons, null, 1) + ';\n');
fs.copyFileSync(path.join(nm, '@tabler/icons/LICENSE'), path.join(root, 'src/renderer/vendor/tabler-icons-LICENSE.txt'));

// Bundled fonts (SIL Open Font License). family -> [fontsource package, weights]
const FONTS = {
  'Inter': ['inter', [400, 600, 800]],
  'Oswald': ['oswald', [400, 600]],
  'Bebas Neue': ['bebas-neue', [400]],
  'Montserrat': ['montserrat', [400, 600, 800]],
  'Playfair Display': ['playfair-display', [400, 700]],
  'Roboto Condensed': ['roboto-condensed', [400, 700]],
};
const fontDir = path.join(root, 'src/renderer/fonts');
fs.mkdirSync(fontDir, { recursive: true });
let css = '/* Generated by scripts/vendor-assets.mjs from @fontsource (SIL OFL 1.1). Do not edit. */\n';
for (const [family, [pkg, weights]] of Object.entries(FONTS)) {
  for (const w of weights) {
    const file = `${pkg}-latin-${w}-normal.woff2`;
    fs.copyFileSync(path.join(nm, '@fontsource', pkg, 'files', file), path.join(fontDir, file));
    css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:block;src:url('./${file}') format('woff2');}\n`;
  }
  const lic = path.join(nm, '@fontsource', pkg, 'LICENSE');
  if (fs.existsSync(lic)) fs.copyFileSync(lic, path.join(fontDir, `${pkg}-LICENSE.txt`));
}
fs.writeFileSync(path.join(fontDir, 'fonts.css'), css);
console.log(`vendored ${Object.keys(icons).length} icons and ${Object.keys(FONTS).length} font families`);
